tiq_login/urls.py
from django.conf.urls.defaults import *
from settings import PATH_TO_THIS_MODULE

urlpatterns = patterns(PATH_TO_THIS_MODULE + '.views',
   (r'login', 'login'),
   (r'logout', 'logout'),
   (r'password_change', 'password_change'),
   (r'password_change_done', 'password_change_done'),
   (r'', 'login')
)

urls.py
from django.conf.urls.defaults import *
import settings

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
   (r'^user/', include('dfs_contact_web_lookup.tiq_login.urls')),
   (r'^contacts/', include('dfs_contact_web_lookup.contacts.urls')),
   (r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/Users/mlmiller/django-projects/dfs_contact_web_lookup/site_media/'}),
   (r'', 'tiq_login.views.login'),
)

tiq_login/models.py
from django.db import models
from django.contrib.auth.models import User 

class TiqUserProfile(models.Model):
   user = models.ForeignKey(User, unique=True)
   session_id = models.CharField(max_length=200)

tiq_login/forms.py
from django import forms

class PasswordChangeForm(forms.Form):
   
   username = forms.CharField(max_length=16)
   old_password = forms.CharField(max_length=16, widget=forms.PasswordInput)
   new_password_1 = forms.CharField(max_length=16, widget=forms.PasswordInput)
   new_password_2 = forms.CharField(max_length=16, widget=forms.PasswordInput)
   
   def clean(self):
      
      if (self.cleaned_data['new_password_1'] != self.cleaned_data['new_password_2']):
         raise forms.ValidationError("New Passwords must Match")

      return self.cleaned_data
      

tiq_login/views.py
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm
from django.contrib.auth.tokens import default_token_generator
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response
from django.contrib.sites.models import Site, RequestSite
from django.http import HttpResponseRedirect, Http404
from django.template import RequestContext
from django.utils.http import urlquote, base36_to_int
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User
from django.views.decorators.cache import never_cache
from tiqLibraries.tiqErrors import TiqPasswordExpiredError
from tiq_login import getSessionRpcClient
from django.core.urlresolvers import reverse
from settings import *
from forms import PasswordChangeForm

def login(request, template_name=TIQ_LOGIN_TEMPLATE_LOGIN, redirect_field_name=REDIRECT_FIELD_NAME):
    "Displays the login form and handles the login action."

    redirect_to = request.REQUEST.get(REDIRECT_FIELD_NAME, '')
    
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)

        try:
           if form.is_valid():
               # Light security check -- make sure redirect_to isn't garbage.
               if not redirect_to or '//' in redirect_to or ' ' in redirect_to:
                   redirect_to = LOGIN_REDIRECT_URL
               from django.contrib.auth import login
               login(request, form.get_user())
               
               if request.session.test_cookie_worked():
                   request.session.delete_test_cookie()
               return HttpResponseRedirect(redirect_to)

        except TiqPasswordExpiredError, e:
           return HttpResponseRedirect(reverse(PATH_TO_THIS_MODULE + '.views.password_change'))
     
    else:
       form = AuthenticationForm(request)

    request.session.set_test_cookie()
    if Site._meta.installed:
        current_site = Site.objects.get_current()
    else:
        current_site = RequestSite(request)
    
    return render_to_response(template_name, {
        'form': form,
        redirect_field_name: redirect_to,
        'site_name': current_site.name,
    }, context_instance=RequestContext(request))

login = never_cache(login)


def logout(request, next_page=None, template_name=TIQ_LOGIN_TEMPLATE_LOGGED_OUT):
    "Logs out the user and displays 'You are logged out' message."

    profile = request.user.get_profile()

    sessionRpcClient = getSessionRpcClient(profile.session_id)
    sessionRpcClient.execute('logout')
  
    profile.session_id = ''
    profile.save()

    from django.contrib.auth import logout
    logout(request)
    if next_page is None:
        return render_to_response(template_name, {'title': _('Logged out'), 'login_link': LOGIN_URL}, context_instance=RequestContext(request))
    else:
        # Redirect to this page until the session has been cleared.
        return HttpResponseRedirect(next_page or request.path)

def logout_then_login(request, login_url=None):
    "Logs out the user if he is logged in. Then redirects to the log-in page."
    if not login_url:
        login_url = LOGIN_URL
    return logout(request, login_url)

def redirect_to_login(next, login_url=None, redirect_field_name=REDIRECT_FIELD_NAME):
    "Redirects the user to the login page, passing the given 'next' page"
    if not login_url:
        login_url = LOGIN_URL
    return HttpResponseRedirect('%s?%s=%s' % (login_url, urlquote(redirect_field_name), urlquote(next)))


def password_change(request, template_name=TIQ_LOGIN_TEMPLATE_PASSWORD_CHANGE,
                    post_change_redirect=LOGIN_REDIRECT_URL):

    login_error = None

    if request.method == "POST":

       form = PasswordChangeForm(request.POST)
       if form.is_valid():
          
          # TODO TIQ PASSWORD CHANGE CODE HERE
          username = form.cleaned_data['username']
          old_password = form.cleaned_data['old_password']
          new_password = form.cleaned_data['new_password_1']
          
          sessionRpcClient = getSessionRpcClient()
          try:
             sessionRpcClient.changePassword(username, old_password, new_password)
          except Exception, e:
             form = PasswordChangeForm()
             login_error = "Your username and old password are incorrect."
          else:
             # not catching errors here, assuming that if the password change succeeded that this will too
             from django.contrib.auth import authenticate, login
             user = authenticate(username=username, password=new_password)
             login(request, user)
             return HttpResponseRedirect(post_change_redirect)
      
    else:
        form = PasswordChangeForm()
        
    return render_to_response(template_name, {
        'form': form, 'login_error': login_error
    }, context_instance=RequestContext(request))


def password_change_done(request, template_name=TIQ_LOGIN_TEMPLATE_PASSWORD_CHANGE_DONE):
    return render_to_response(template_name, context_instance=RequestContext(request))

templates/tiq_login/logged_out.html
{% extends "base.html" %}
{% load i18n %}

{% block page_title %}Login{% endblock page_title %}

{% block body %}
<h1>You've Been Logged Out</h1>
<div class="content">
<p>{% trans "Thanks for spending some quality time with the Web site today." %}</p>

<p><a href="{{ login_link }}">{% trans 'Log in again' %}</a></p>
</div>
{% endblock %}

templates/tiq_login/login.html
{% extends "base.html" %}
{% load i18n %}

{% block page_title %}Login{% endblock page_title %}

{% block body %}

<h1>Log In</h1>
<div class="content">
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<div id="content-main">
<form action="{{ app_path }}" method="post" id="login-form">
  <div class="form-row">
    <label for="id_username">{% trans 'Username:' %}</label> <input type="text" name="username" id="id_username" />
  </div>
  <div class="form-row">
    <label for="id_password">{% trans 'Password:' %}</label> <input type="password" name="password" id="id_password" />
    <input type="hidden" name="this_is_the_login_form" value="1" />
  </div>
  <div class="submit-row">
    <input type="hidden" name="next" value="{{ next }}" />
    <label>&nbsp;</label><input type="submit" value="{% trans 'Log in' %}" />
  </div>
</form>

<script type="text/javascript">
document.getElementById('id_username').focus()
</script>
</div>
</div>
{% endblock body %}

templates/tiq_login/password_change.html
{% extends "base.html" %}
{% load i18n %}

{% block page_title %}Change Password{% endblock page_title %}

{% block body %}

<h1>{% trans 'Password change' %}</h1>

<p>{% trans "Please enter your username and old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}</p>

{% if login_error %}
<p>{{ login_error }}</p>
{% endif %}

{% if form.errors %}
<p>{{ form.errors }}</p>
{% endif %}

<div id="content-main">
<form action="" method="post">
  <div class="form-row">
    {{ form.username.errors }}
    <label for="id_username">{% trans 'Username:' %}</label>{{ form.username}}
  </div>
  <div class="form-row">
    {{ form.old_password.errors }}
    <label for="id_old_password">{% trans 'Old Password:' %}</label>{{ form.old_password}}
  </div>
  <div class="form-row">
    {{ form.new_password_1.errors }}
    <label for="id_new_password_1">{% trans 'New Password:' %}</label>{{ form.new_password_1}}
  </div>
  <div class="form-row">
    {{ form.new_password_2.errors }}
    <label for="id_new_password_2">{% trans 'Retype New Password:' %}</label>{{ form.new_password_2}}
  </div>
  <div class="submit-row">
    <input type="hidden" name="next" value="{{ next }}" />
    <label>&nbsp;</label><input type="submit" value="{% trans 'Change Password' %}" />
  </div>
</form>

{% endblock %}

templates/tiq_login/password_change_done.html
{% extends "base.html" %}
{% load i18n %}

{% block page_title %}Login{% endblock page_title %}

{% block body %}

<h1>{% trans 'Password change successful' %}</h1>

<p>{% trans 'Your password was changed.' %}</p>

{% endblock %}