contacts/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('dfs_contact_web_lookup.contacts.views',
   (r'search', 'search'),
   (r'detail/(?P<contact_id>\d+)', 'detail'),
   (r'', 'search')
)

tiq_login/urls.py
from django.conf.urls.defaults import *
from settings import PATH_TO_THIS_MODULE

urlpatterns = patterns(PATH_TO_THIS_MODULE + '.views',
   (r'login', 'login'),
   (r'logout', 'logout'),
   (r'password_change', 'password_change'),
   (r'password_change_done', 'password_change_done'),
   (r'', 'login')
)

urls.py
from django.conf.urls.defaults import *
import settings

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
   (r'^user/', include('dfs_contact_web_lookup.tiq_login.urls')),
   (r'^contacts/', include('dfs_contact_web_lookup.contacts.urls')),
   (r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/Users/mlmiller/django-projects/dfs_contact_web_lookup/site_media/'}),
   (r'', 'tiq_login.views.login'),
)

contacts/models.py
from django.db import models
from django.contrib.auth.models import User 

class CachedContacts(models.Model):
   user = models.ForeignKey(User)
   contact_id = models.IntegerField()
   contact_name = models.CharField(max_length=32)
   viewed =  models.IntegerField()
   last_viewed = models.DateTimeField(auto_now=True)

contacts/forms.py
from django import forms

class ContactSearchForm(forms.Form):
   
   search_term = forms.CharField(max_length=16)

contacts/views.py
from django.shortcuts import render_to_response, get_object_or_404
from dfs_contact_web_lookup.tiq_login import getSessionRpcClient
from dfs_contact_web_lookup.contacts.models import CachedContacts

def compare_by (fieldname):
   def compare_two_dicts (a, b):
      return cmp(a[fieldname], b[fieldname])
   return compare_two_dicts


def search(request):
   
   from forms import ContactSearchForm
   
   if request.method == 'POST':
      
      form = ContactSearchForm(request.POST)
      if form.is_valid():
         
         search_term = form.cleaned_data['search_term']
         
         sessionRpc = getSessionRpcClient(request.user.get_profile().session_id)
         results = sessionRpc.execute('addressBook.searchContacts', {'term': search_term})
         results.sort(compare_by(u'name'))
         # [{u'type': u'contact', u'id': 32516, u'name': u'Ann Harvey'}, ... ]
         return render_to_response('contacts/search_results.html', {'search_term': search_term, 'results':results, 'showlogout':True})
      
   else:
      form = ContactSearchForm()
   
   recent = CachedContacts.objects.order_by('last_viewed').reverse()[:5]
   favorite = CachedContacts.objects.order_by('viewed').reverse()[:5]
   
   return render_to_response('contacts/search.html', {'form': form, 'showlogout':True, 'recent':recent, 'favorite':favorite})


def detail(request, contact_id=None):
   
   if contact_id == None:
      form = ContactSearchForm()
      return render_to_response('contacts/search.html', {'form': form})

   
   sessionRpc = getSessionRpcClient(request.user.get_profile().session_id)
   
   contactDetails = sessionRpc.execute('addressBook.getContactDetails', {'id': contact_id})
   contactInfo = sessionRpc.execute('query.getContactInfo', {'id': contact_id})

   try:
       cc = CachedContacts.objects.get(contact_id=contact_id, user=request.user)
       cc.viewed = cc.viewed + 1
       cc.save()
   except CachedContacts.DoesNotExist:
       cc = CachedContacts()
       cc.user = request.user
       cc.contact_id = contact_id
       cc.contact_name = contactDetails['name']
       cc.viewed =  1
       cc.save()
       pass
   
   return render_to_response('contacts/detail.html', {'contactDetails': contactDetails, 'contactInfo': contactInfo, 'showlogout':True})
   

templates/contacts/detail.html
{% extends "base.html" %}
{% load i18n %}

{% block page_title %}Login{% endblock page_title %}

{% block body %}

<h1>{{ contactDetails.name }}
</h1>
<div class="content">
<p><a href="/contacts/search">Back to Search</a></p>

{% if contactInfo.phone %}
<h2>Phone</h2>
<ul class="resultList">
{% for p in contactInfo.phone %}
<li><a href="tel:{{p.phone}}">{{p.phone}}</a> <span class="meta">({{p.description}})</span></li>
{% endfor %}
</ul>
{% endif %}

{% if contactInfo.email %}
<h2>Email</h2>
<ul>
{% for e in contactInfo.email %}
<li><a href="mailto:{{e.email}}">{{e.email}}</a> <span class="meta">({{e.description}})</span></li>
{% endfor %}
</ul>
{% endif %}

{% if contactInfo.address %}
<h2>Address</h2>
<ul>
{% for a in contactInfo.address %}
<li>{{a.address}} <span class="meta">({{a.description}})</span></li>
{% endfor %}
</ul>
{% endif %}

{% if contactInfo.im %}
<h2>IM</h2>
<ul>
{% for i in contactInfo.im %}
<li>{{i.name}} <span class="meta">({{i.description}})</span></li>
{% endfor %}
</ul>
{% endif %}

<p class="meta">Last updated {{ contactDetails.updated_on }} by {{ contactDetails.updated_by_screenname }}.</p>

</div>
{% endblock body %}

templates/contacts/search.html
{% extends "base.html" %}
{% load i18n %}

{% block page_title %}Login{% endblock page_title %}

{% block body %}

<h1>Contact Search</h1>
<div class="content">

    <form action="/contacts/search" method="POST">
        <div class="fieldWrapper">
            {{ form.search_term.errors }}
            <label for="id_search_term">Search:</label>
            {{ form.search_term }}
        </div>
        <p><input type="submit" value="Search" /></p>
    </form>

<h2>Recently Viewed</h2>
<ul class="searchResultList">
{% for r in recent %}
<li><a href="/contacts/detail/{{ r.contact_id }}">{{ r.contact_name }}</a></li>
{% endfor %}
</ul>

<h2>Most Viewed</h2>
<ul class="searchResultList">
{% for f in favorite %}
<li><a href="/contacts/detail/{{ f.contact_id }}">{{ f.contact_name }}</a></li>
{% endfor %}
</ul>

<script type="text/javascript">
document.getElementById('id_search_term').focus()
</script>
</div>
{% endblock body %}

templates/contacts/search_results.html
{% extends "base.html" %}
{% load i18n %}

{% block page_title %}Login{% endblock page_title %}

{% block body %}

<h1>Contact Search Results</h1>
<div class="content">
<p><a href="/contacts/search">Back to Search</a></p>
<p>You searched for:</p>
<h2>{{ search_term }}</h2>
<!-- # [{u'type': u'contact', u'id': 000, u'name': u'Contact Name'}, ... ] -->
<ul class="searchResultList">
{% for r in results %}

<li><a href="/contacts/detail/{{ r.id }}">{{ r.name }}</a></li>

{% endfor %}
</ul>
</div>
{% endblock body %}